### ISSUE TITLE
Generante token

### ISSUE THREAD

**Issue by Robson96** [paseto-toolkit/jpaseto#16]
already downloaded all the dependencies but still keeps giving this exception

Exception in thread "main" dev.paseto.jpaseto.PasetoKeyException: Failed to generate Ed25519 key pair
	at dev.paseto.jpaseto.lang.Keys.keyPairFor(Keys.java:60)
	at com.prototype.token.GenerateToken.apply(GenerateToken.java:19)
	at com.prototype.token.GenerateToken.main(GenerateToken.java:33)
Caused by: java.security.NoSuchAlgorithmException: Ed25519 KeyPairGenerator not available
	at java.base/java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:236)
	at dev.paseto.jpaseto.lang.Keys.keyPairFor(Keys.java:57)
	... 2 more

**Comment by bdemers** [comment]
Are you using Java 8?  If so you will need to include Bouncy Castle as a dependency (or you could use Java 11+)

https://github.com/paseto-toolkit/jpaseto#paseto-format-support

If that doesn't help, let me know what OS and Java version you are using, and I'll take a look

**Comment by Robson96** [comment]
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

openSUSE Tumbleweed 64 bits 


pom.xml
<dependency>
      <groupId>dev.paseto</groupId>
      <artifactId>jpaseto-api</artifactId>
      <version>0.6.0</version>
    </dependency>
    <dependency>
      <groupId>dev.paseto</groupId>
      <artifactId>jpaseto-impl</artifactId>
      <version>0.6.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>dev.paseto</groupId>
      <artifactId>jpaseto-jackson</artifactId>
      <version>0.6.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>dev.paseto</groupId>
      <artifactId>jpaseto-bouncy-castle</artifactId>
      <version>0.6.0</version>
    </dependency>
    <dependency>
      <groupId>dev.paseto</groupId>
      <artifactId>jpaseto-sodium</artifactId>
      <version>0.6.0</version>
    </dependency>

**Comment by Robson96** [comment]
I also installed libsodium natively, but I tried to follow the tutorial to get a public v2 token, but I found it a bit outdated or confusing!

**Comment by bdemers** [comment]
Ahh, I think I see the issue.

If you create key pair before initializing the Paseto Builder/Parser then Bouncy Castle isn't initialized yet.

The quick work around is add `Security.addProvider(new BouncyCastleProvider());` before you call `Keys. keyPairFor`

We'll get this fixed.  Which tutorial are you using and I'll double-check that too

**Comment by Robson96** [comment]
here on github and an article that I think you wrote!

https://blog.bdemers.io/categories/jpaseto/

**Comment by Robson96** [comment]
so was my test code

@Override
    public String apply(User user) {
        KeyPair keyPair = Keys.keyPairFor(Version.V2);

        String compact = Pasetos.V2.PUBLIC.builder()
                .setPrivateKey(keyPair.getPrivate())
                .setSubject(user.getName())
                .compact();
        return compact;
    }

that I managed to understand from the tutorials

**Comment by Robson96** [comment]
you say you have to have libsodium, but you install it automatically
https://github.com/paseto-toolkit/jpaseto/blob/main/src/ci/libsodium.sh

but there is a dependency on libsodium, you don't understand

**Comment by Robson96** [comment]
I think you just need to update the documentation, the sample codes!

And now after your tip my code worked!
Thanks!
