### ISSUE TITLE
Cast Exception in String to Paseto

### ISSUE THREAD

**Issue by anand-mm** [paseto-toolkit/jpaseto#193]
java.lang.ClassCastException: java.lang.String cannot be cast to dev.paseto.jpaseto.Paseto

I tried using instanceof keyword in java it did not work:

```java
    public Integer pasetoclaims(Object clientToken, String param) {
        Integer result = null;
        Paseto token = null;
        try {
            if(clientToken instanceof Paseto)
                token = (Paseto) clientToken;
            if (param.contains("name"))
                result = token.getClaims().get("name", Integer.class);
            else
                result = token.getClaims().get(param, Integer.class);
        } catch (Exception e) {
           e.printStackTrace();
        }
        return result;
    }
```

I also tried using getclass but it did not work,

```java
    public Integer pasetoclaims(Object clientToken, String param) {
        Integer result = null;
        Paseto token = null;
        try {
            if(clientToken.getClass().equals(Paseto.class))     //This is where i have used getclass
                token = (Paseto) clientToken;
            if (param.contains("name"))
                result = token.getClaims().get("name", Integer.class);
            else
                result = token.getClaims().get(param, Integer.class);
        } catch (Exception e) {
           e.printStackTrace();
        }
        return result;
    }
```

Can anyone suggest how to cast it in a proper way . Thanks in advance.

**Comment by bdemers** [comment]
Sorry @anand-mm, I think I'm missing something.  
Are you trying to cast a `String` to a `Paseto` object directly?
If so please look at: https://github.com/paseto-toolkit/jpaseto#paseto-read

Otherwise, can you create an example project on GitHub that demos the problem and link it here?

**Comment by bdemers** [comment]
No, that is not possible Java.

Take a look at this section of the docs to learn how to parse a [String] PASETO token: https://github.com/paseto-toolkit/jpaseto#paseto-read
