### ISSUE TITLE
Can't use KeyResolver with DefaultPasetoParserBuilder

### ISSUE THREAD

**Issue by michael-albinson-sn** [paseto-toolkit/jpaseto#4]
Hello,

I am trying to use a custom `KeyResolver` with the `DefaultPasetoParserBuilder`, but I get an exception: 
> java.lang.IllegalArgumentException: PasetoParser must be configure with a public key (for public tokens) and/or a sharedSecret (for local tokens).

This exception is coming from line 77 of `DefaultPasetoParserBuilder`: https://github.com/paseto-toolkit/jpaseto/blob/b8cdc203886a31e06f5788d199237bb55e95e32c/impl/src/main/java/dev/paseto/jpaseto/impl/DefaultPasetoParserBuilder.java#L77 :
`Assert.isTrue( publicKey != null || sharedSecret != null,"...");` 

This needs to change to this so that you can use a key resolver:
`Assert.isTrue(keyResolver != null || publicKey != null || sharedSecret != null,"...");` 

Please let me know if there are any questions on this, as I would like it to be resolved ASAP!

**Comment by michael-albinson-sn** [comment]
My use case:
```
return Pasetos.parserBuilder()
	.setKeyResolver(new MyKeyResolver())
	.build()
	.parse(tokenString);
```

**Comment by michael-albinson-sn** [comment]
Stack trace:
```
java.lang.IllegalArgumentException: PasetoParser must be configure with a public key (for public tokens) and/or a sharedSecret (for local tokens).
	at dev.paseto.jpaseto.lang.Assert.isTrue(Assert.java:32)
	at dev.paseto.jpaseto.impl.DefaultPasetoParserBuilder.build(DefaultPasetoParserBuilder.java:77)
```

**Comment by bdemers** [comment]
Thanks @michael-albinson-sn !
I fixed this in a380230f0b9540583cc681cf9b011ad7e7442ddf
I'll cut a release shortly!

**Comment by bdemers** [comment]
The release is out: https://github.com/paseto-toolkit/jpaseto/releases/tag/jpaseto-0.4.0
I could take an hour or so before it syncs to Maven Central

Thanks again @michael-albinson-sn

**Comment by michael-albinson-sn** [comment]
Cheers, thanks for the quick response and fix @bdemers!
